os: linux
language: android
jdk: oraclejdk8
env:
  global:
  - ANDROID_API=28
  - ANDROID_BUILD_API=28.0.3
  - NDK_API=21.3.6528147
  - REPO=t-e-l/tel
  - APK_NAME=TEL-${TRAVIS_BUILD_NUMBER}
  - DEV_NAME=DEV-BUILD-${TRAVIS_BUILD_NUMBER}
  - BAR_NAME=DEV-BAR-BUILD-${TRAVIS_BUILD_NUMBER}
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-${ANDROID_BUILD_API}
  - android-${ANDROID_API}
  - extra-android-m2repository
  - extra
  - extra-google-m2repository
  licenses:
  - android-sdk-license-.+
  - android-ndk-license-.+
  - android-sdk-preview-license-.+
  - google-gdk-license-.+
before_cache: "-rm -f $HOME/.gradle/caches/modules-2/modules-2.lock -rm -fr $HOME/.gradle/caches/*/plugin-resolution/"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
script:
- "./gradlew :app:assembleRelease"
before_install:
- openssl aes-256-cbc -K $encrypted_c80f59e584b7_key -iv $encrypted_c80f59e584b7_iv -in keystore.jks.enc -out keystore.jks -d
- mkdir -p $ANDROID_HOME/licenses
- echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
- echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
- echo y | sdkmanager "platforms;android-${ANDROID_API}"
- echo y | sdkmanager "ndk-bundle"
- echo y | sdkmanager "ndk;${NDK_API}"
- cd ./bootstrap && bash build_bootstrap.sh && cd ..
before_deploy:
- find . -name '*.apk'
- mv ./app/build/outputs/apk/release/app-release-unsigned.apk app-release.apk
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore keystore.jks -storepass
  $keystore_password -keypass $keystore_alias_password app-release.apk $keystore_alias
- jarsigner -verify app-release.apk
- "${ANDROID_HOME}build-tools/${ANDROID_BUILD_API}/zipalign -v 4 app-release.apk ${APK_NAME}.apk"
- git config --local user.name "v1nc"
- git config --local user.email "github@reckendrees.systems"
- git tag "TEL-${TRAVIS_BUILD_NUMBER}"
deploy:
  - provider: releases
    api_key:
      secure: BiJyG4KWJNgtPa7C5cEHcj2LMhBvUp6yyXAFNrfPJ2ZdSewyoDlJHJmyPk3htRtwmYPdiXDWEOj9LV10851MZCKB+c/cyQY9m5/5Zlr15qYtfIIWvX/0RPHt3qUMRw+8b6UNE8xNenq4jzLMDTnkvs3RkrXBbpTR4Iiu/POCWvBUMiOcB0MeLXosVkgoNrPol2ovQXL6yw8QihzbfdfquirObdF4MdES10LDZBJfiw8A+6+IzwqBSLONbbtM9scxN1FnIG1PGcxHKPugD6TbtUmUoqjWFzxrU/Hrb1dK7zZYaEzX8kESV8R7F/I+cvKj+kcAb1/FOMCdAafB6axyZ/Bl1YoW9EyK7OAV4EUdAhATXymRbBbzYI99uce5cniJlmgahWx+mI89I7VKmmpwKppiLnF3ZrrXOESxYomy8g9CtoHBIjeicc/hwmU03BkzQjSu48EVmU5o+FjpkOCJ249qLikNVX+MsBPKjDanx2uuSjZDv/skLyMv4sSY1rEUVrAxTxkhT6x8BywJ9QO/I+kyo4rl/d70iElKW6JapiGDr8mOMgOYxBVtENTdEzDy845WB2wZopZ6bOKkm9hD/1sKvIP/bgMhEYli3FyY5NMz8fsWUVu+uW+AO6Aecve/PkLzbVerZWXmoYzKoMB7k9kwEnwO3NSiA6+UxteiGeo=
    file: ${APK_NAME}.apk
    skip_cleanup: true
    on:
      repo: ${REPO}
      branch: master

  - provider: releases
    api_key:
      secure: BiJyG4KWJNgtPa7C5cEHcj2LMhBvUp6yyXAFNrfPJ2ZdSewyoDlJHJmyPk3htRtwmYPdiXDWEOj9LV10851MZCKB+c/cyQY9m5/5Zlr15qYtfIIWvX/0RPHt3qUMRw+8b6UNE8xNenq4jzLMDTnkvs3RkrXBbpTR4Iiu/POCWvBUMiOcB0MeLXosVkgoNrPol2ovQXL6yw8QihzbfdfquirObdF4MdES10LDZBJfiw8A+6+IzwqBSLONbbtM9scxN1FnIG1PGcxHKPugD6TbtUmUoqjWFzxrU/Hrb1dK7zZYaEzX8kESV8R7F/I+cvKj+kcAb1/FOMCdAafB6axyZ/Bl1YoW9EyK7OAV4EUdAhATXymRbBbzYI99uce5cniJlmgahWx+mI89I7VKmmpwKppiLnF3ZrrXOESxYomy8g9CtoHBIjeicc/hwmU03BkzQjSu48EVmU5o+FjpkOCJ249qLikNVX+MsBPKjDanx2uuSjZDv/skLyMv4sSY1rEUVrAxTxkhT6x8BywJ9QO/I+kyo4rl/d70iElKW6JapiGDr8mOMgOYxBVtENTdEzDy845WB2wZopZ6bOKkm9hD/1sKvIP/bgMhEYli3FyY5NMz8fsWUVu+uW+AO6Aecve/PkLzbVerZWXmoYzKoMB7k9kwEnwO3NSiA6+UxteiGeo=
    file: ${APK_NAME}.apk
    name: ${DEV_NAME}
    tag_name: ${DEV_NAME}
    body: |
      DEV-${DEV_NAME}
      This is a dev build!
      Dont use it!
      Dont ask anybody about it!
    skip_cleanup: true
    prerelease: true
    on:
      repo: ${REPO}
      branch: dev
  - provider: releases
    api_key:
      secure: BiJyG4KWJNgtPa7C5cEHcj2LMhBvUp6yyXAFNrfPJ2ZdSewyoDlJHJmyPk3htRtwmYPdiXDWEOj9LV10851MZCKB+c/cyQY9m5/5Zlr15qYtfIIWvX/0RPHt3qUMRw+8b6UNE8xNenq4jzLMDTnkvs3RkrXBbpTR4Iiu/POCWvBUMiOcB0MeLXosVkgoNrPol2ovQXL6yw8QihzbfdfquirObdF4MdES10LDZBJfiw8A+6+IzwqBSLONbbtM9scxN1FnIG1PGcxHKPugD6TbtUmUoqjWFzxrU/Hrb1dK7zZYaEzX8kESV8R7F/I+cvKj+kcAb1/FOMCdAafB6axyZ/Bl1YoW9EyK7OAV4EUdAhATXymRbBbzYI99uce5cniJlmgahWx+mI89I7VKmmpwKppiLnF3ZrrXOESxYomy8g9CtoHBIjeicc/hwmU03BkzQjSu48EVmU5o+FjpkOCJ249qLikNVX+MsBPKjDanx2uuSjZDv/skLyMv4sSY1rEUVrAxTxkhT6x8BywJ9QO/I+kyo4rl/d70iElKW6JapiGDr8mOMgOYxBVtENTdEzDy845WB2wZopZ6bOKkm9hD/1sKvIP/bgMhEYli3FyY5NMz8fsWUVu+uW+AO6Aecve/PkLzbVerZWXmoYzKoMB7k9kwEnwO3NSiA6+UxteiGeo=
    file: ${APK_NAME}.apk
    name: ${BAR_NAME}
    tag_name: ${BAR_NAME}
    body: |
      DEV-${BAR_NAME}
      This is a dev build!
      Dont use it!
      Dont ask anybody about it!
    skip_cleanup: true
    prerelease: true
    on:
      repo: ${REPO}
      branch: suggestion_bar
